spring.application.name=grupo35

# Server
server.port=${SERVER_PORT:8080}

# DataSource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=challenge

# Flyway
spring.flyway.schemas=challenge
spring.flyway.default-schema=challenge

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
jwt.secret=minha-chave-secreta-super-segura-grupo35-fiap-2024
jwt.expiration=86400000